version: "3.4"  
services:
  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass Pass1234!
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
    restart: on-failure
    ports:
      - "6379:6379"
    depends_on:
      - db
    networks:
      - visualreader
  db:
    # image: "mcr.microsoft.com/mssql/server:2022-latest"
    image: "mcr.microsoft.com/mssql/server:2019-CU16-ubuntu-20.04"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass1234!"
      ACCEPT_EULA: "Y"
      MSSQL_DB: dct
    networks:
      - visualreader
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      ConnectionStrings__Default: "Server=db;Database=visualreader;User=sa;Password=Pass1234!;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
      Redis__Host: "redis"
      Redis__Ssl: "false"
      Redis__Password: "Pass1234!"
      Redis__Database: "1"
      ServerEndpoint: "db"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - visualreader
  migration:
    build:
      context: .
      dockerfile: Dockerfile-migration
    restart: on-failure
    depends_on:
      - db
    networks:
      - visualreader
networks:
  visualreader: