FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

 ENV PATH="$PATH:/root/.dotnet/tools"

 RUN dotnet tool install dotnet-roundhouse -g --version 1.3.1

WORKDIR .
COPY scripts/. ./scripts/

# Uncomment if you need to insert the test data
# COPY tests/IntegrationTest/sql/afterUp ./sql/afterUp

ENTRYPOINT [ "rh", "--connectionstring=Server=db;Database=visualreader;User=sa;Password=Pass1234!;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;", "--connstringadmin=Server=db;Database=Master;User=sa;Password=Pass1234!;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;", "--sqlfilesdirectory=scripts", "--environmentnames=DEV", "--databaseType=sqlserver", "--silent", "--withtransaction=true" ]