CREATE TABLE book(
[id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY
);
CREATE TABLE chapter(
[id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY
);
CREATE TABLE post(
[id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY
);
CREATE TABLE comment (
	[id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
	[created_utc] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[updated_utc] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[content] NVARCHAR(MAX) ,
	[book_id] UNIQUEIDENTIFIER FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE,
	[post_id] UNIQUEIDENTIFIER FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE,
	[chapter_id] UNIQUEIDENTIFIER FOREIGN KEY (chapter_id) REFERENCES chapter(id) ON DELETE CASCADE,
	[user_id] UNIQUEIDENTIFIER FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);